char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - R_Collar
  - R_Shoulder
  - R_Elbow
  - L_Collar
  - L_Shoulder
  - L_Elbow
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - R_Hip
  - R_Knee
  - R_Ankle
  - L_Hip
  - L_Knee
  - L_Ankle
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Pelvis
  - Spine1
  - Spine2
  - Spine3
  - Neck
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Pelvis
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - L_Elbow
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - R_Elbow
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - L_Ankle
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - R_Ankle
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - R_Ankle
    - R_Knee
    - R_Hip
  - - L_Ankle
    - L_Knee
    - L_Hip
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - L_Shoulder
  - L_Elbow
  left_foot: !!python/tuple
  - L_Knee
  - L_Ankle
  left_hand: !!python/tuple
  - L_Shoulder
  - L_Elbow
  left_knee: !!python/tuple
  - L_Hip
  - L_Knee
  torso: !!python/tuple
  - Pelvis
  - Spine1
  neck: !!python/tuple
  - Spine3
  - Neck
  right_elbow: !!python/tuple
  - R_Shoulder
  - R_Elbow
  right_foot: !!python/tuple
  - R_Knee
  - R_Ankle
  right_hand: !!python/tuple
  - R_Shoulder
  - R_Elbow
  right_knee: !!python/tuple
  - R_Hip
  - R_Knee
char_runtime_checks:
  - - above
    - neck
    - right_shoulder
    - left_shoulder
