scene:
  ANIMATED_CHARACTERS:
    - character_cfg: examples/characters/kaira-kun/char_cfg.yaml
      motion_cfg: examples/config/motion/my_motion.yaml
      retarget_cfg: examples/config/retarget/my_motion.yaml
view:
  CAMERA_POS: [0.0, 0.7, 2.0]
  CAMERA_FWD: [0.0, 0.5, 8.0]
controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: ./video.mp4
  OUTPUT_VIDEO_CODEC: avc1
